mongo-container:
  image: mongo:3
  environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
  ports:
    - "27017:27017"
  volumes:
    - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
  command: mongod
