spring:
  freemarker:
    cache: false
    suffix: '.ftl'
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'admin'
      username: 'admin'
      password: 'admin'

sectors:
  insertion:
    run: true
    files: 'sectors.json'
