spring:
  freemarker:
    cache: false
    suffix: '.ftl'
  data:
    mongodb:
      host: 'mongodb'
      port: 27017
      database: 'admin'
      username: 'sectors'
      password: 'sectors'

sectors:
  insertion:
    run: true
    files: 'sectors.json'
